# Generated by Django 4.0.4 on 2022-06-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
